---
dependencies:
  - role: core/container
    container_name: cadvisor
    container_image: gcr.io/cadvisor/cadvisor:latest
    container_privileged: true
    container_networks:
      - name: "{{ traefik_internal_network_name }}"
        ipv4_address: "{{ ipv4_address }}"
        aliases:
          - "{{ container_name }}"
    container_ports:
      - 8081:8080/tcp
    container_envs:
      TZ: "{{ timezone }}"
    container_devices:
      - /dev/kmsg:/dev/kmsg
    container_volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
      - /etc/localtime:/etc/localtime:ro
    container_labels:
      traefik.http.routers.cadvisor.rule: Host(`{{ url }}`)
      traefik.http.services.cadvisor.loadbalancer.server.port: "8080"
