---
- name: Ensure required directories are present
  ansible.builtin.file:
    dest: "{{ item.dest | default(item) }}"
    state: directory
    mode: 0775
    owner: "{{ item.owner | default(default_owner.name) }}"
    group: "{{ item.group | default(default_group.name) }}"
  loop:
    - dest: "{{ docker_dir }}/{{ container_name }}"
      owner: "{{ guid }}"
    - "{{ mergerfs_root }}/Media/TV"
    - "{{ mergerfs_root }}/Downloads/TV"

- name: Ensure {{ container_name }} container is up and running
  community.docker.docker_container:
    name: "{{ container_name }}"
    state: started
    restart_policy: unless-stopped
    image: "{{ container_image }}"
    network_mode: "{{ vpn_docker_network }}"
    networks:
      - name: "{{ traefik_internal_network_name }}"
        ipv4_address: "{{ ipv4_address }}"
        aliases:
          - "{{ container_name }}"
    env:
      PUID: "{{ guid }}"
      PGID: "{{ default_group.id }}"
      TZ: "{{ timezone }}"
    volumes:
      - "{{ docker_dir }}/{{ container_name }}:/config"
      - "{{ mergerfs_root }}/Media/TV:/data/media/tv"
      - "{{ mergerfs_root }}/Downloads/TV:/data/torrents/tv"
      - /etc/localtime:/etc/localtime:ro
    labels: "{{ container_labels }}"
