---
- name: Ensure cron jobs are enabled
  ansible.builtin.cron:
    name: "{{ item.name }}"
    job: "{{ item.job | join('; ') }}"
    state: "{{ item.state | default('present') }}"
    month: "{{ item.month | default('*') }}"
    weekday: "{{ item.weekday | default('*') }}"
    day: "{{ item.day | default('*') }}"
    hour: "{{ item.hour | default('*') }}"
    minute: "{{ item.minute | default('*') }}"
  loop: "{{ cron_jobs }}"
  when: cron_jobs[0] is defined
