---
- name: netplan apply
  ansible.builtin.command:
    cmd: netplan apply
  changed_when: false

- name: remove default user
  ansible.builtin.user:
    name: ubuntu
    state: absent

- name: powersaving systemd reload
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: restarted
    enabled: true
    daemon_reload: true
  loop:
    - powertop
    - powertop.timer
    - cpupower-min
    - cpupower-min.timer
