---
dependencies:
  - role: core/container
    container_name: portainer
    container_image: portainer/portainer-ce:latest
    container_directories:
      - dest: "{{ docker_dir }}/{{ container_name }}"
        owner: "{{ guid }}"
    container_networks:
      - name: "{{ traefik_internal_network_name }}"
        ipv4_address: "{{ ipv4_address }}"
        aliases:
          - "{{ container_name }}"
    container_envs:
      PUID: "{{ guid }}"
      PGID: "{{ default_group.id }}"
      TZ: "{{ timezone }}"
    container_volumes:
      - "{{ docker_dir }}/{{ container_name }}:/data"
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    container_labels:
      traefik.http.routers.portainer.rule: Host(`{{ url }}`)
      traefik.http.services.portainer.loadbalancer.server.port: "9000"
