---
- name: Ensure nvidia-smi is installed
  when: nvidia_smi_is_installed is undefined
  block:
    - name: Check nvidia-smi command
      ansible.builtin.command: nvidia-smi
      changed_when: false
      check_mode: false
      ignore_errors: true
      register: _nvidia_smi_is_installed

    - name: Set nvidia-smi fact
      ansible.builtin.set_fact:
        nvidia_smi_is_installed: "{{ (_nvidia_smi_is_installed.rc == 0) and (_nvidia_smi_is_installed.stderr_lines | length == 0) }}"

- name: Check if nvidia_gpu_exporter is installed
  ansible.builtin.stat:
    path: "{{ nvidia_gpu_exporter_binary_install_dir }}/nvidia_gpu_exporter"
  check_mode: false
  register: _nvidia_gpu_exporter_is_installed
  when: nvidia_smi_is_installed

- name: Get currently installed nvidia_gpu_exporter version (if any)
  ansible.builtin.command:
    cmd: "{{ nvidia_gpu_exporter_binary_install_dir }}/nvidia_gpu_exporter --version"
    warn: false
  changed_when: false
  check_mode: false
  register: _nvidia_gpu_exporter_current_version_output
  when:
    - nvidia_smi_is_installed
    - _nvidia_gpu_exporter_is_installed.stat.exists

- name: Get latest version of nvidia_gpu_exporter
  when:
    - nvidia_gpu_exporter_version == "latest"
    - nvidia_smi_is_installed
  delegate_to: localhost
  become: false
  run_once: true
  block:
    - name: Get latest release
      ansible.builtin.uri:
        url: "https://api.github.com/repos/utkuozdemir/nvidia_gpu_exporter/releases/latest"
        method: GET
        return_content: true
        status_code: 200
        body_format: json
        user: "{{ lookup('env', 'GITHUB_USER') | default(omit) }}"
        password: "{{ lookup('env', 'GITHUB_TOKEN') | default(omit) }}"
      register: _latest_release
      until: _latest_release.status == 200
      retries: 5

    - name: "Set nvidia_gpu_exporter version to {{ _latest_release.json.tag_name[1:] }}"
      ansible.builtin.set_fact:
        nvidia_gpu_exporter_version: "{{ _latest_release.json.tag_name[1:] }}"

- name: Get checksum for nvidia_gpu_exporter release
  when: nvidia_smi_is_installed
  delegate_to: localhost
  become: false
  block:
    - name: Get checksum list from github
      ansible.builtin.set_fact:
        _checksums: "{{ lookup('url', 'https://github.com/utkuozdemir/nvidia_gpu_exporter/releases/download/v' + nvidia_gpu_exporter_version + '/checksums.txt', wantlist=True) | list }}"
      run_once: true

    - name: "Get checksum for {{ ansible_architecture }} architecture"
      ansible.builtin.set_fact:
        nvidia_gpu_exporter_checksum: "{{ item.split(' ')[0] }}"
      when: "('linux_' + ansible_architecture + '.tar.gz') in item"
      loop: "{{ _checksums }}"
