---
- name: Download nvidia_gpu_exporter binary to local folder
  become: false
  delegate_to: localhost
  ansible.builtin.get_url:
    url: "https://github.com/utkuozdemir/nvidia_gpu_exporter/releases/download/v{{ nvidia_gpu_exporter_version }}/nvidia_gpu_exporter_{{ nvidia_gpu_exporter_version }}_linux_{{ ansible_architecture }}.tar.gz"
    dest: "/tmp/nvidia_gpu_exporter_{{ nvidia_gpu_exporter_version }}_linux_{{ ansible_architecture }}.tar.gz"
    checksum: "sha256:{{ nvidia_gpu_exporter_checksum }}"
    mode: 0644
  register: _download_binary
  until: _download_binary is succeeded
  retries: 5
  delay: 2
  check_mode: false

- name: Unpack nvidia_gpu_exporter binary
  become: false
  delegate_to: localhost
  ansible.builtin.unarchive:
    src: "/tmp/nvidia_gpu_exporter_{{ nvidia_gpu_exporter_version }}_linux_{{ ansible_architecture }}.tar.gz"
    dest: "/tmp"
    creates: "/tmp/nvidia_gpu_exporter"
  check_mode: false

- name: Propagate node_exporter binaries
  ansible.builtin.copy:
    src: "/tmp/nvidia_gpu_exporter"
    dest: "{{ nvidia_gpu_exporter_binary_install_dir }}/nvidia_gpu_exporter"
    mode: 0755
    owner: root
    group: root
  notify: restart nvidia_gpu_exporter
