---
- import_tasks: before-install.yml
- import_tasks: user.yml
  when: nvidia_smi_is_installed
- import_tasks: install.yml
  when:
    - nvidia_smi_is_installed
    - >-
      (not _nvidia_gpu_exporter_is_installed.stat.exists)
      or ((_nvidia_gpu_exporter_current_version_output.stderr_lines | length > 0) and (_nvidia_gpu_exporter_current_version_output.stderr_lines[0].split(" ")[2] != nvidia_gpu_exporter_version))
      or ((_nvidia_gpu_exporter_current_version_output.stdout_lines | length > 0) and (_nvidia_gpu_exporter_current_version_output.stdout_lines[0].split(" ")[2] != nvidia_gpu_exporter_version))
- import_tasks: configure.yml
  when: nvidia_smi_is_installed
