---
#
# Prometheus
#
prometheus_version: 2.36.2
prometheus_web_listen_address: "0.0.0.0:9090"
prometheus_storage_retention: 3d
prometheus_scrape_configs:
  - job_name: node
    metrics_path: "/metrics"
    static_configs:
      - targets:
          - 192.168.56.10:9100
          - 192.168.56.11:9100
  - job_name: docker
    metrics_path: /metrics
    static_configs:
      - targets:
          - 192.168.56.10:8081
#
# Grafana
#
grafana_address: "0.0.0.0"
grafana_port: 3000
grafana_security:
  admin_user: admin
  admin_password: admin
grafana_datasources:
  - name: Prometheus
    type: prometheus
    url: "http://0.0.0.0:9090"
    basicAuth: false
grafana_dashboards_dir: "{{ playbook_dir }}/files/dashboards"
