---
#
# Misc
#
docker_dir: /opt/docker/data
github_token: "{{ lookup('env', 'github_token') }}"
ssh_public_key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
vpn_docker_network: "{{ vpn_docker_network_enabled | ternary('container:open-vpn', 'default') }}"
#
# system/users
#
system_users:
  - name: "{{ username }}"
    password: "{{ password | password_hash('sha512', 'ansible') }}"
    groups:
      - users
      - "{{ sudo_group }}"
    append: true
  - name: dockeruser
    uid: "{{ guid | int }}"
    groups:
      - users
      - "{{ sudo_group }}"
    append: true
  - name: grafana
    uid: "{{ grafana_uid }}"
    groups:
      - users
  - name: prometheus
    uid: "{{ prometheus_uid }}"
    groups:
      - users
#
# system/packages
#
system_packages:
  - htop
  - git
  - neofetch
  - tmux
  - rsync
  - iotop
  - ncdu
  - cronie
  - python3.10
  - python3.11
  - python3-pip
  - dnf-plugins-core
  - ca-certificates
  - curl
system_python_pip_packages:
  - docker
#
# docker/engine
#
docker_users:
  - "{{ username }}"
  - dockeruser
#
# network/security
#
security_firewall_rules:
  - port: 9100/tcp
    state: enabled
    permanent: true
  - port: 3000/tcp
    state: enabled
    permanent: true
  - port: 9090/tcp
    state: enabled
    permanent: true
#
# system/wireguard
#
wireguard_host: wireguard.local
wireguard_port: 51869
wireguard_subnet: 10.13.13.0/24
#
# Prometheus
#
prometheus_web_address: "0.0.0.0:9090"
prometheus_storage_retention: 3d
prometheus_scrape_configs:
  - job_name: node
    metrics_path: "/metrics"
    static_configs:
      - targets:
          - 192.168.50.3:9100
          - 192.168.50.4:9100
  - job_name: docker
    metrics_path: /metrics
    static_configs:
      - targets:
          - 192.168.50.3:8081
#
# Grafana
#
grafana_use_provisioning: true
grafana_address: "0.0.0.0"
grafana_port: 3000
grafana_security:
  admin_user: admin
  admin_password: admin
grafana_datasources:
  - name: Prometheus
    type: prometheus
    url: "http://192.168.50.4:9090"
    basicAuth: false
