---
dependencies:
  - role: core/container
    container_name: deluge
    container_image: lscr.io/linuxserver/deluge:latest
    container_network_mode: "{{ vpn_docker_network }}"
    container_directories:
      - dest: "{{ docker_dir }}/{{ container_name }}"
        owner: "{{ guid }}"
      - dest: "{{ docker_dir }}/{{ container_name }}/data"
        owner: "{{ guid }}"
      - dest: "{{ docker_dir }}/{{ container_name }}/config"
        owner: "{{ guid }}"
      - "{{ mergerfs_root }}/Downloads/Movies"
      - "{{ mergerfs_root }}/Downloads/Books"
      - "{{ mergerfs_root }}/Downloads/TV"
    container_envs:
      PUID: "{{ guid }}"
      PGID: "{{ default_group.id }}"
      TZ: "{{ timezone }}"
    container_volumes:
      - "{{ docker_dir }}/{{ container_name }}/config:/config"
      - "{{ docker_dir }}/{{ container_name }}/data:/data"
      - "{{ mergerfs_root }}/Downloads/TV:/data/torrents/tv"
      - "{{ mergerfs_root }}/Downloads/Books:/data/torrents/books"
      - "{{ mergerfs_root }}/Downloads/Movies:/data/torrents/movies"
      - /etc/localtime:/etc/localtime:ro
    container_labels:
      traefik.http.routers.deluge.rule: Host(`{{ url }}`)
      traefik.http.services.deluge.loadbalancer.server.port: "8112"
