---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v4.3.0
    hooks:
      - id: check-case-conflict
      - id: check-json
      - id: pretty-format-json
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: detect-private-key
      - id: check-added-large-files
      - id: mixed-line-ending
      - id: sort-simple-yaml
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.27.1
    hooks:
      - id: yamllint
  - repo: https://github.com/ansible/ansible-lint.git
    rev: v6.4.0
    hooks:
      - id: ansible-lint
        args: [--offline]
        files: \.(yaml|yml)$
