---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v5.0.0
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-toml
      - id: end-of-file-fixer
      - id: detect-private-key
      - id: mixed-line-ending
      - id: sort-simple-yaml
      - id: pretty-format-json
        args:
          - --indent=4
          - --no-ensure-ascii
      - id: check-added-large-files
        args:
          - --maxkb=1000
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.37.1
    hooks:
      - id: yamllint
  - repo: https://github.com/ansible/ansible-lint.git
    rev: v25.6.1
    hooks:
      - id: ansible-lint
        args: [--offline]
        files: \.(yaml|yml)$
