---
- name: Setup ssh connection
  hosts: all
  tags: always
  gather_facts: false

  tasks:
    - name: ssh | import tasks
      ansible.builtin.import_tasks: tasks/ssh-juggle-port.yml

- name: Reboot if needed
  hosts: all
  become: true

  pre_tasks:
    - name: reboot | import tasks
      ansible.builtin.import_tasks: tasks/reboot-required.yml

  roles:
    #
    # System
    #
    - role: system/users
      tags:
        - users
        - system
    - role: system/packages
      tags:
        - packages
        - system
    - role: system/powersaving
      tags:
        - powersaving
        - system
      when: powersaving_enabled | default(false) | bool
    #
    # Docker
    #
    - role: docker/engine
      tags: docker
    - role: docker/nvidia
      tags: docker
      when: nvidia_docker_enabled | default(false) | bool
    - role: docker/backup
      tags: docker
      when: docker_backup_enabled | default(false) | bool
    #
    # Network
    #
    - role: network/firewall
      tags:
        - firewall
        - network

- name: Configure filesystem and shares
  hosts: home
  become: true
  tags: filesystem

  vars:
    ansible_selinux:
      status: disabled

  roles:
    #
    # Filesystem
    #
    - role: mrlesmithjr.zfs
      tags: zfs
      when: nas_stuff_enabled | default(false) | bool
    - role: filesystem/mergerfs
      tags: mergerfs
      when: nas_stuff_enabled | default(false) | bool
    - role: bertvv.samba
      tags: samba
      when: samba_enabled | default(false) | bool
    - role: filesystem/cron
      tags: cron

- name: Setup apps and network
  hosts: all
  become: true
  tags: apps

  roles:
    #
    # Network
    #
    - role: network/letsencrypt
      tags:
        - letsencrypt
        - duskdns
        - network
      when:
        - inventory_hostname in groups["monitoring"]
        - letsencrypt_enabled | default(false) | bool
    - role: network/traefik
      tags:
        - traefik
        - network
      when:
        - inventory_hostname in groups["home"]
        - traefik_enabled | default(false) | bool
    - role: network/openvpn
      tags:
        - open-vpn
        - network
      when:
        - inventory_hostname in groups["home"]
        - vpn_docker_network_enabled | default(false) | bool
    - role: network/wireguard
      tags:
        - wireguard
        - network
      when:
        - inventory_hostname in groups["monitoring"]
        - vpn_enabled | default(false) | bool
    #
    # Apps/System
    #
    - role: apps/system/diun
      tags:
        - diun
        - apps/system
      when: diun_enabled | default(false) | bool
    - role: apps/system/portainer
      tags:
        - portainer
        - apps/system
    #
    # Apps/Services
    #
    - role: apps/services/pihole
      tags:
        - pihole
        - apps/services
      when: inventory_hostname in groups["monitoring"]
    - role: apps/services/transmission
      tags:
        - transmission
        - apps/services
      when: inventory_hostname in groups["home"]
    #
    # Apps/Media
    #
    - role: apps/media/bazarr
      tags:
        - bazarr
        - apps/media
      when: inventory_hostname in groups["home"]
    - role: apps/media/jackett
      tags:
        - jackett
        - apps/media
      when: inventory_hostname in groups["home"]
    - role: apps/media/jellyfin
      tags:
        - jellyfin
        - apps/media
      when: inventory_hostname in groups["home"]
    - role: apps/media/plex
      tags:
        - plex
        - apps/media
      when: inventory_hostname in groups["home"]
    - role: apps/media/prowlarr
      tags:
        - prowlarr
        - apps/media
      when: inventory_hostname in groups["home"]
    - role: apps/media/radarr
      tags:
        - radarr
        - apps/media
      when: inventory_hostname in groups["home"]
    - role: apps/media/readarr
      tags:
        - readarr
        - apps/media
      when: inventory_hostname in groups["home"]
    - role: apps/media/sonarr
      tags:
        - sonarr
        - apps/media
      when: inventory_hostname in groups["home"]
    #
    # Dashboard
    #
    - role: dashboard/homer
      tags:
        - homer
        - dashboard
      when:
        - inventory_hostname in groups["home"]
        - dashboard_enabled | default(false) | bool

- name: Setup metric exporters
  hosts: all
  become: true
  tags: monitoring

  roles:
    #
    # System monitoring
    #
    - role: geerlingguy.node_exporter
      tags:
        - node
        - exporters
    - role: monitoring/exporters/nvidia_gpu
      tags:
        - nvidia
        - exporters
      when: nvidia_docker_enabled | default(false) | bool
    - role: monitoring/exporters/cadvisor
      tags:
        - cadvisor
        - exporters
    #
    # Disks monitoring
    #
    - role: monitoring/smart
      tags:
        - smart
        - monitoring
      when:
        - inventory_hostname in groups["home"]
        - smart_monitoring_enabled | default(false) | bool
    - role: stuvusit.smartd
      tags:
        - smart
        - monitoring
      when:
        - inventory_hostname in groups["home"]
        - smart_monitoring_enabled | default(false) | bool

- name: Setup monitoring system
  hosts: monitoring
  become: true
  tags: monitoring

  roles:
    - role: monitoring/prometheus
      tags: prometheus
    - role: monitoring/grafana
      tags: grafana

- name: Setup security for all hosts
  hosts: all
  become: true
  tags: security

  roles:
    - role: geerlingguy.security
      when: security_enabled | default(false) | bool
    - role: security/endlessh
      tags: security/endlessh
      when:
        - security_enabled | default(false) | bool
        - endlessh_enabled | default(false) | bool
