---
collections:
  - name: ansible.posix
  - name: community.general
  - name: community.docker
  - name: community.grafana
roles:
  - name: bertvv.samba
  - name: mrlesmithjr.zfs
  - name: stuvusit.smartd
  - name: geerlingguy.ntp
  - name: geerlingguy.security
  - name: geerlingguy.node_exporter
