---
- name: Import docker tasks
  ansible.builtin.import_tasks: docker.yaml
- name: Import datasources tasks
  when: grafana_datasources | length > 0
  ansible.builtin.import_tasks: datasources.yaml
- name: Import dashboards tasks
  when: grafana_dashboards_dir | length > 0
  ansible.builtin.import_tasks: dashboards.yaml
