---
- name: Include RedHat specific tasks
  ansible.builtin.include_tasks: setup-RedHat.yaml
  when: ansible_os_family == 'RedHat'

- name: Include Debian specific tasks
  ansible.builtin.include_tasks: setup-Debian.yaml
  when: ansible_os_family == 'Debian'

- name: Ensure docker folders exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    owner: root
    group: root
  loop:
    - /etc/docker
    - /etc/systemd/system/docker.service.d

- name: Copy docker daemon template
  ansible.builtin.template:
    src: "{{ (nvidia_docker_enabled | default(false) | bool) | ternary('nvidia-daemon.json.j2', 'daemon.json.j2')}}"
    dest: /etc/docker/daemon.json
    mode: 0644
    owner: root
    group: root
  notify: restart docker

- name: Copy docker systemd override conf
  ansible.builtin.copy:
    src: override.conf
    dest: /etc/systemd/system/docker.service.d/override.conf
    mode: 0644
    owner: root
    group: root
  notify: restart docker

- name: Ensure docker is started and enabled on boot
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: true

- name: Ensure handlers are flushed now
  ansible.builtin.meta: flush_handlers

- name: Ensure docker users are added to the docker group
  ansible.builtin.user:
    name: "{{ item }}"
    groups: docker
    append: true
  loop: "{{ docker_users }}"
