---
- name: Run geerlingguy.docker role
  ansible.builtin.include_role:
    name: geerlingguy.docker
  vars:
    docker_edition: ce
    docker_packages:
        - "docker-{{ docker_edition }}"
        - "docker-{{ docker_edition }}-cli"
        - "docker-{{ docker_edition }}-rootless-extras"
    docker_packages_state: present
    docker_service_manage: true
    docker_service_state: started
    docker_service_enabled: true
    docker_install_compose: true
