---
- name: Ensure required directories are present
  ansible.builtin.file:
    dest: "{{ item.dest | default(item) }}"
    state: directory
    mode: "{{ item.mode | default('755') }}"
  loop:
    - "{{ docker_dir }}/{{ container_name }}"
    - "{{ docker_dir }}/{{ container_name }}/configurations"
    - dest: "{{ docker_dir }}/{{ container_name }}/letsencrypt"
      mode: '600'

- name: Copy static configuration
  ansible.builtin.template:
    src: traefik.yml.j2
    dest: "{{ docker_dir }}/{{ container_name }}/traefik.yml"
    mode: 0644
  register: traefik_static_config

- name: Generate dynamic configuration
  ansible.builtin.template:
    src: dynamic.yml.j2
    dest: "{{ docker_dir }}/{{ container_name }}/configurations/dynamic.yml"
    mode: 0644
  register: traefik_dynamic_config

- name: "Ensure container is up and running: {{ container_name }}"
  community.docker.docker_container:
    name: "{{ container_name }}"
    state: started
    image: "{{ container_image }}"
    pull: true
    restart_policy: unless-stopped
    networks:
      - name: "{{ traefik_internal_network_name }}"
        ipv4_address: "{{ ipv4_address }}"
        aliases:
          - "{{ container_name }}"
    env:
      TZ: "{{ timezone }}"
      DUCKDNS_TOKEN: "{{ duckdns_token }}"
    ports:
      - 80:80/tcp
      - 443:443/tcp
      - 8080:8080/tcp
      - 8082:8082/tcp
    volumes:
      - "{{ docker_dir }}/{{ container_name }}/traefik.yml:/etc/traefik/traefik.yml:ro"
      - "{{ docker_dir }}/{{ container_name }}/configurations:/configurations"
      - "{{ docker_dir }}/{{ container_name }}/letsencrypt:/letsencrypt"
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels: "{{ container_labels }}"
    recreate: "{{ (traefik_static_config is changed) or (traefik_dynamic_config is changed) }}"
