---
- name: Ensure flaresolverr is up and running
  community.docker.docker_container:
    name: flaresolverr
    state: started
    restart_policy: unless-stopped
    image: ghcr.io/flaresolverr/flaresolverr:latest
    network_mode: "{{ vpn_docker_network }}"
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 1
    env:
      LOG_LEVEL: info
      LOG_HTML: "false"
      CAPTCHA_SOLVER: none
      TZ: "{{ timezone }}"
