---
# VPN/Algo
algo_endpoint: "1.2.3.4"
algo_install_path: /opt/algo
# Also add default variables from defaults/main.yml in roles
# VPN/Iptables
iptables_rules:
  - comment: "Ansible Managed: Allow scraping metrics from node-exporter"
    chain: INPUT
    protocol: tcp
    destination_port: 9100
    jump: ACCEPT
  - comment: "Ansible Managed: Allow SSH with different port"
    chain: INPUT
    protocol: tcp
    destination_port: "{{ security_ssh_port }}"
    ctstate: NEW,ESTABLISHED
    jump: ACCEPT
iptables_block: |
  # Allow scraping metrics from node-exporter
  -A INPUT -p tcp --dport 9100 -j ACCEPT
  # Allow SSH with different port
  -A INPUT -p tcp --dport {{ security_ssh_port }} --ctstate NEW,ESTABLISHED -j ACCEPT
