---
dependencies:
  - role: core/container
    container_name: bazarr
    container_image: lscr.io/linuxserver/bazarr:latest
    container_network_mode: "{{ vpn_docker_network }}"
    container_directories:
      - dest: "{{ docker_dir }}/{{ container_name }}"
        owner: "{{ guid }}"
      - "{{ mergerfs_root }}/Media/Movies"
      - "{{ mergerfs_root }}/Media/TV"
      - "{{ mergerfs_root }}/Downloads/Movies"
      - "{{ mergerfs_root }}/Downloads/TV"
    container_envs:
      PUID: "{{ guid }}"
      PGID: "{{ default_group.id }}"
      TZ: "{{ timezone }}"
    container_volumes:
      - "{{ docker_dir }}/{{ container_name }}:/config"
      - "{{ mergerfs_root }}/Media/Movies:/data/media/movies"
      - "{{ mergerfs_root }}/Media/TV:/data/media/tv"
      - "{{ mergerfs_root }}/Downloads/Movies:/data/torrents/movies"
      - "{{ mergerfs_root }}/Downloads/TV:/data/torrents/tv"
      - /etc/localtime:/etc/localtime:ro
    container_labels:
      traefik.http.routers.bazarr.rule: Host(`{{ url }}`)
      traefik.http.services.bazarr.loadbalancer.server.port: "6767"
