---
url: "traefik.{{ host_local }}"
ipv4_address: "{{ traefik_internal_network_base }}.22"

dashboard_name: Traefik
dashboard_category: system
dashboard_subtitle: Networking Stack That Just Works

container_name: traefikdash
container_image: traefik:v2.10.1
container_labels: |
  {
    "traefik.enable": "true",
    "traefik.http.routers.{{ container_name }}.rule": "Host(`{{ url }}`)",
    "traefik.http.routers.{{ container_name }}.service": "api@internal",
    "traefik.http.routers.{{ container_name }}.tls": "true",
    "traefik.http.routers.{{ container_name }}.entrypoints": "websecure",
    "traefik.http.routers.{{ container_name }}.tls.certresolver": "myresolver",
    "traefik.http.services.{{ container_name }}.loadbalancer.server.port": "8080",
  }
