---
dependencies:
  - role: core/container
    container_name: cadvisor
    container_image: "{{ (go_arch == 'amd64') | ternary('gcr.io/cadvisor/cadvisor:latest', 'zcube/cadvisor:latest') }}"
    container_privileged: true
    container_ports:
      - 8081:8080/tcp
    container_envs:
      TZ: "{{ timezone }}"
    container_devices:
      - /dev/kmsg:/dev/kmsg
    container_volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    container_ssl_enabled: false
    container_labels: {}
