---
#
# Enabling goes here
#
docker_backup_enabled: true
#
# Misc
#
docker_dir: /opt/docker/data
hostname: "{{ inventory_hostname }}"
github_token: "{{ lookup('env', 'github_token') }}"
ssh_public_key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
vpn_docker_network: "{{ vpn_docker_network_enabled | ternary('container:open-vpn', 'default') }}"
#
# system/users
#
sambashare_group_name: sambashare
system_users:
  - name: "{{ username }}"
    password: "{{ password | password_hash('sha512', 'ansible') }}"
    groups:
      - users
      - sambashare
      - "{{ sudo_group }}"
    append: true
  - name: dockeruser
    uid: "{{ guid | int }}"
    groups:
      - users
      - sambashare
      - "{{ sudo_group }}"
    append: true
  - name: "{{ sambashare_group_name }}"
    gid: 1003
    groups:
      - "{{ sambashare_group_name }}"
#
# system/packages
#
system_packages:
  - htop
  - stow
  - git
  - neofetch
  - neovim
  - tmux
  - mosh
  - rsync
  - iotop
  - ncdu
  - cronie
  - hddtemp
  - initscripts
  - samba
  - python3.10
  - python3.11
  - python3-pip
  - dnf-plugins-core
  - ca-certificates
  - curl
  # Urls
  - name: https://github.com/trapexit/mergerfs/releases/download/2.33.5/mergerfs-2.33.5-1.fc32.x86_64.rpm
    disable_gpg_check: true
  - name: https://zfsonlinux.org/fedora/zfs-release-2-2.fc37.noarch.rpm
    disable_gpg_check: true
  - kernel-devel
  - zfs
system_python_pip_packages:
  - docker
system_modprobe_modules:
  - zfs
system_services:
  - smb
#
# docker/engine
#
docker_users:
  - "{{ username }}"
  - dockeruser
#
# MergerFS
#
mergerfs_root: "/home/{{ username }}/tmp"
#
# bertvv.samba
#
samba_server_string: "{{ hostname }}"
samba_users:
  - name: "{{ username }}"
    password: "{{ password }}"
samba_global_include: global-include.conf
samba_apple_extensions: true
samba_mitigate_cve_2017_7494: false
samba_server_max_protocol: "SMB3"
samba_server_min_protocol: "SMB3"
samba_shares:
  - name: Media
    guest_ok: false
    public: false
    read_only: false
    writable: true
    browseable: true
    directory_mode: "0775"
    owner: "{{ default_owner.name }}"
    group: "{{ sambashare_group_name }}"
    path: "{{ mergerfs_root }}/Media"
    valid_users: "{{ samba_users | map(attribute='name') | join (', ') }}"
    write_list: "{{ samba_users | map(attribute='name') | join (', ') }}"
  - name: Downloads
    guest_ok: false
    public: false
    read_only: false
    writable: true
    browseable: true
    directory_mode: "0775"
    owner: "{{ default_owner.name }}"
    group: "{{ sambashare_group_name }}"
    path: "{{ mergerfs_root }}/Downloads"
    valid_users: "{{ samba_users | map(attribute='name') | join (', ') }}"
    write_list: "{{ samba_users | map(attribute='name') | join (', ') }}"
#
# filesystem/cron
#
cron_jobs:
  - name: backup docker dir
    minute: 10
    hour: "*/2"
    job:
      - !unsafe docker stop $(docker ps --format "{{ .ID }} {{ .Names }}" | awk '$2 != "open-vpn" { print $1 }')
      - rsync -avz --delete --exclude cache {{ docker_dir }} {{ mergerfs_root }}/docker-data
      - docker start $(docker ps -a -q)
#
# network/security
#
security_firewall_rules:
  - service: samba
    state: enabled
    permanent: true
  - port: 9100/tcp
    state: enabled
    permanent: true
  - port: grafana
    state: enabled
    permanent: true
  - service: prometheus
    state: enabled
    permanent: true
  - rich_rule: rule service name="exporter" audit limit value="1/m" accept
    state: enabled
    permanent: true
security_sebooleans:
  - samba_enable_home_dirs
  - samba_export_all_rw
#
# network/traefik
#
traefik_internal_network_name: traefik-proxy
traefik_internal_network_subnet: 172.28.0.0/16
traefik_internal_network_iprange: 172.28.13.0/24
traefik_internal_network_gateway: 172.28.13.1
traefik_internal_network_base: "{{ '.'.join(traefik_internal_network_iprange.split('.')[0:3]) }}"
#
# dashboard/homer
#
homer_title: Well, he's very dear to my heart.
dashboard_subtitle: You don't remember anything, do you?
homer_external_applications:
  - name: Grafana
    url: "http://grafana.{{ host_local }}"
    logo: assets/tools/homer-icons/grafana.png
    subtitle: Monitoring solution for every database
    category: system
