---
url: "portainer.{{ host_local }}"
ipv4_address: "{{ traefik_internal_network_base }}.19"

dashboard_name: Portainer
homer_category: system
homer_subtitle: Service delivery platform for containerized applications
