---
- name: Ensure required directories are present
  ansible.builtin.file:
    dest: "{{ item.dest | default(item) }}"
    state: directory
    mode: 0775
    owner: "{{ item.owner | default(default_owner.name) }}"
    group: "{{ item.group | default(default_group.name) }}"
  loop:
    - dest: "{{ docker_dir }}/{{ container_name }}"
      owner: "{{ guid }}"
    - "{{ mergerfs_root }}/Media/Movies"
    - "{{ mergerfs_root }}/Media/TV"

- name: Ensure {{ container_name }} container is up and running
  community.docker.docker_container:
    name: "{{ container_name }}"
    state: started
    restart_policy: unless-stopped
    image: "{{ container_image }}"
    pull: true
    network_mode: host
    devices:
      - /dev/dri:/dev/dri
    env:
      PUID: "{{ guid }}"
      PGID: "{{ default_group.id }}"
      TZ: "{{ timezone }}"
      VERSION: latest
      NVIDIA_VISIBLE_DEVICES: all
    runtime: "{{ nvidia_docker_enabled | default(false) | bool | ternary('nvidia', '') }}"
    volumes:
      - "{{ docker_dir }}/{{ container_name }}:/config"
      - "{{ mergerfs_root }}/Media/Movies:/movies"
      - "{{ mergerfs_root }}/Media/TV:/tv"
