---
- name: Ensure rules v4 are present in iptables
  ansible.builtin.iptables:
    comment: "{{ item.comment }}"
    chain: "{{ item.chain }}"
    protocol: "{{ item.protocol }}"
    destination_port: "{{ item.destination_port }}"
    jump: "{{ item.jump }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ iptables_rules }}"

- name: Ensure rules are present in /etc/iptables/rules.v4
  ansible.builtin.blockinfile:
    path: /etc/iptables/rules.v4
    insertafter: -A INPUT -p tcp --dport 22
    block: "{{ iptables_block }}"
