---
dependencies:
  - role: core/container
    container_name: "{{ twingate_container_name }}"
    container_image: twingate/connector:1
    container_envs:
      TENANT_URL: "{{ twingate_tenant_url }}"
      ACCESS_TOKEN: "{{ twingate_access_token }}"
      REFRESH_TOKEN: "{{ twingate_refresh_token }}"
      DNS_SERVER: "{{ twingate_dns_server }}"
      TWINGATE_LABEL_HOSTNAME: "`hostname`"
      TWINGATE_LOG_ANALYTICS: v1
    container_sysctls:
      net.ipv4.ping_group_range: "0 2147483647"
    container_ssl_enabled: false
    container_labels: {}
