---
- name: reload firewalld
  ansible.builtin.command:
    cmd: firewall-cmd --reload
  changed_when: false
  check_mode: false

- name: sleep 10 seconds
  ansible.builtin.command:
    cmd: sleep 10
  changed_when: false
  check_mode: false
