---
- name: Set the name of a sudo group
  ansible.builtin.set_fact:
    sudo_group: sudo

- name: Ensure these users exist
  ansible.builtin.user:
    name: "{{ item.name }}"
    groups: "{{ item.groups }}"
    uid: "{{ item.uid | default(omit) }}"
    password: "{{ item.password | default(omit) }}"
    update_password: "{{ item.update_password | default('on_create') }}"
    state: "{{ item.state | default('present') }}"
    append: "{{ item.append | default(true) | bool }}"
  when: item.create | default(true) | bool
  loop: "{{ home_system_users }}"

- name: Ensure these groups exist
  ansible.builtin.group:
    name: "{{ item.name }}"
    gid: "{{ item.gid | default(omit) }}"
    state: "{{ item.state | default('present') }}"
  when: item.create | default(true) | bool
  loop: "{{ home_system_users }}"

- name: "Ensure group {{ sambashare_group_name }} exists"
  ansible.builtin.group:
    name: "{{ sambashare_group_name }}"
    gid: "{{ sambashare_gid }}"
    state: present
  when: samba_enabled | default(false) | bool

- name: "Append the {{ sambashare_group_name }} group"
  ansible.builtin.user:
    name: "{{ item.name }}"
    groups: "{{ sambashare_group_name }}"
    append: true
  when: samba_enabled | default(false) | bool
  loop: "{{ home_system_users }}"

- name: Allow 'sudo' group to have passwordless sudo
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%{{ sudo_group }}'
    line: '%{{ sudo_group }} ALL=(ALL) NOPASSWD: ALL'
    validate: '/usr/sbin/visudo -cf %s'

- name: "Copy the public SSH key for {{ username }}"
  ansible.posix.authorized_key:
    user: "{{ username }}"
    state: present
    key: "{{ ssh_public_key }}"
  notify: remove default user

- name: Set the default shell
  ansible.builtin.user:
    name: "{{ item.name }}"
    shell: "{{ item.shell | default('/bin/bash') }}"
  when: item.create | default(true) | bool
  loop: "{{ home_system_users }}"

- name: Disable cron e-mail notifications
  ansible.builtin.cron:
    name: MAILTO
    user: "{{ username }}"
    env: true
    job: ""
