---
dependencies:
  - role: core/container
    container_name: lazylibrarian
    container_image: lscr.io/linuxserver/lazylibrarian:latest
    container_network_mode: "{{ vpn_docker_network }}"
    container_directories:
      - dest: "{{ docker_dir }}/{{ container_name }}"
        owner: "{{ guid }}"
      - "{{ mergerfs_root }}/Media/Books"
      - "{{ mergerfs_root }}/Downloads/Books"
    container_envs:
      PUID: "{{ guid }}"
      PGID: "{{ default_group.id }}"
      TZ: "{{ timezone }}"
      DOCKER_MODS: linuxserver/calibre-web:calibre
    container_volumes:
      - "{{ docker_dir }}/{{ container_name }}:/config:rw"
      - "{{ mergerfs_root }}/Media/Books:/books:rw"
      - "{{ mergerfs_root }}/Downloads/Books:/downloads:rw"
    container_labels: |
      {
        "traefik.enable": "true",
        "traefik.http.routers.{{ container_name }}.rule": "Host(`{{ url }}`)",
        "traefik.http.services.{{ container_name }}.loadbalancer.server.port": "5299",
      }
