---
- name: Ensure extra packages are installed
  ansible.builtin.dnf:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('present') }}"
    disable_gpg_check: "{{ item.disable_gpg_check | default(false) | bool }}"
  loop: "{{ system_packages }}"

- name: Ensure pip packages are installed
  ansible.builtin.pip:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ system_python_pip_packages }}"

- name: Ensure modules are added to modprobe
  community.general.modprobe:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ system_modprobe_modules }}"

- name: Ensure services are started and enabled
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: true
  loop: "{{ system_services }}"
