---
- name: Include RedHat specific tasks
  ansible.builtin.include_tasks: setup-RedHat.yaml
  when: ansible_os_family == 'RedHat'

- name: Include Debian specific tasks
  ansible.builtin.include_tasks: setup-Debian.yaml
  when: ansible_os_family == 'Debian'

- name: Ensure pip packages are installed
  ansible.builtin.pip:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ system_python_pip_packages }}"

- name: Ensure modules are added to modprobe
  community.general.modprobe:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ system_modprobe_modules }}"

- name: Ensure services are started and enabled
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: true
  loop: "{{ system_services }}"
