---
- name: Ensure extra packages are installed
  ansible.builtin.apt:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('present') }}"
    update_cache: true
  loop: "{{ system_packages }}"
