---
dependencies:
  - role: core/container
    container_name: readarr
    container_image: lscr.io/linuxserver/readarr:develop
    container_network_mode: "{{ vpn_docker_network }}"
    container_directories:
      - dest: "{{ docker_dir }}/{{ container_name }}"
        owner: "{{ guid }}"
      - "{{ mergerfs_root }}/Media/Books"
      - "{{ mergerfs_root }}/Downloads/Books"
    container_envs:
      PUID: "{{ guid }}"
      PGID: "{{ default_group.id }}"
      TZ: "{{ timezone }}"
    container_volumes:
      - "{{ docker_dir }}/{{ container_name }}:/config"
      - "{{ mergerfs_root }}/Media/Books:/data/media/books"
      - "{{ mergerfs_root }}/Downloads/Books:/data/torrents/books"
      - /etc/localtime:/etc/localtime:ro
    container_labels:
      traefik.http.routers.readarr.rule: Host(`{{ url }}`)
      traefik.http.services.readarr.loadbalancer.server.port: "8787"
