---
url: "bazarr.{{ host_local }}"
ipv4_address: "{{ traefik_internal_network_base }}.10"

dashboard_name: Bazarr
dashboard_category: media
dashboard_subtitle: Download subtitles based on your requirements
