---
- name: "Ensure {{ container_name }} container is up and running"
  community.docker.docker_container:
    name: "{{ container_name }}"
    image: "containrrr/watchtower"
    pull: true
    state: started
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart_policy: unless-stopped
