---
- name: Ensure required directories are present
  ansible.builtin.file:
    dest: "{{ item.dest | default(item) }}"
    state: directory
    mode: 0775
    owner: "{{ item.owner | default(default_owner.name) }}"
    group: "{{ item.group | default(default_group.name) }}"
  loop:
    - dest: "{{ docker_dir }}/{{ container_name }}"
      owner: "{{ guid }}"
    - "{{ mergerfs_root }}/Media/Metadata"
    - "{{ mergerfs_root }}/Media/Cache"
    - "{{ mergerfs_root }}/Media/Transcodes"

- name: Ensure {{ container_name }} container is up and running
  community.docker.docker_container:
    name: "{{ container_name }}"
    state: started
    restart_policy: unless-stopped
    image: "{{ container_image }}"
    pull: true
    networks:
      - name: "{{ traefik_internal_network_name }}"
        ipv4_address: "{{ ipv4_address }}"
        aliases:
          - "{{ container_name }}"
    devices:
      - /dev/dri:/dev/dri
    env:
      PUID: "{{ guid }}"
      PGID: "{{ default_group.id }}"
      TZ: "{{ timezone }}"
      VERSION: latest
      NVIDIA_VISIBLE_DEVICES: all
    runtime: "{{ nvidia_docker_enabled | default(false) | bool | ternary('nvidia', '') }}"
    ports:
      - 7359:7359/udp
      - 1900:1900/udp
    volumes:
      - "{{ docker_dir }}/{{ container_name }}:/config"
      - "{{ mergerfs_root }}/Media:/media"
      - "{{ mergerfs_root }}/Media/Metadata:/metadata"
      - "{{ mergerfs_root }}/Media/Cache:/data/Cache"
      - "{{ mergerfs_root }}/Media/Transcodes:/config/data/transcodes"
      - /etc/localtime:/etc/localtime:ro
    labels: "{{ container_labels }}"
