---
- name: Include RedHat specific tasks
  ansible.builtin.include_tasks: setup-RedHat.yaml
  when: ansible_os_family == 'RedHat'

- name: Include Debian specific tasks
  ansible.builtin.include_tasks: setup-Debian.yaml
  when: ansible_os_family == 'Debian'

- name: Ensure handlers are notified now
  ansible.builtin.meta: flush_handlers
