---
url: "jackett.{{ host_local }}"
ipv4_address: "{{ traefik_internal_network_base }}.11"

dashboard_name: Jackett
homer_category: media
homer_subtitle: Tracker-site-specific http queries

container_name: jackett
container_image: lscr.io/linuxserver/jackett:latest
container_labels:
  traefik.http.routers.jackett.rule: Host(`{{ url }}`)
  traefik.http.services.jackett.loadbalancer.server.port: "9117"
