---
- name: Ensure endlessh is present
  ansible.builtin.package:
    name: endlessh
    state: present

- name: Copy the config file
  ansible.builtin.copy:
    src: files/config
    dest: /etc/endlessh/config
    owner: "{{ default_owner.name }}"
    group: "{{ default_group.name }}"
    mode: 0644
  notify: restart endlessh

- name: Add the net_bind_capability to the executable (for running on port 22)
  ansible.builtin.command:
    cmd: "setcap 'cap_net_bind_service=+ep' /usr/bin/endlessh"
  notify: restart endlessh
  changed_when: false

- name: Add the net_bind_capability to the systemd service (for running on port 22)
  ansible.builtin.lineinfile:
    regexp: "^#AmbientCapabilities.*$"
    line: "AmbientCapabilities=CAP_NET_BIND_SERVICE"
    path: "/usr/lib/systemd/system/endlessh.service"
  notify: restart endlessh

- name: Comment 'PrivateUsers' (for running on port 22)
  ansible.builtin.lineinfile:
    regexp: "^PrivateUsers=true$"
    line: "#PrivateUsers=true"
    path: "/usr/lib/systemd/system/endlessh.service"
  notify: restart endlessh

- name: Add log output
  ansible.builtin.lineinfile:
    regexp: "^StandardOutput.*$"
    line: "StandardOutput=file:/var/log/endlessh"
    path: "/usr/lib/systemd/system/endlessh.service"
  notify: restart endlessh

- name: Start and enable endlessh
  ansible.builtin.service:
    name: endlessh
    state: started
    enabled: true
