---
- name: Include RedHat specific tasks
  ansible.builtin.include_tasks: setup-RedHat.yaml
  when: ansible_os_family == 'RedHat'

- name: Include Debian specific tasks
  ansible.builtin.include_tasks: setup-Debian.yaml
  when: ansible_os_family == 'Debian'

- name: Install the systemd services
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/etc/systemd/system/{{ item | basename }}"
    mode: 0755
    owner: "{{ default_owner.name }}"
    group: "{{ default_group.name }}"
  notify: powersaving systemd reload
  with_fileglob:
    - files/powersaving/*.service
    - files/powersaving/*.timer

- name: Start and enable the systemd services
  ansible.builtin.systemd:
    state: started
    enabled: true
    name: "{{ item }}"
  loop:
    - powertop.timer
    - cpupower-min.timer

- name: Shut down every day (apart from Sunday) at 1:30 AM
  ansible.builtin.cron:
    name: "Power off at night to save energy"
    minute: "30"
    hour: "1"
    weekday: "1-6"
    job: poweroff
